version: '3.4'
networks:
  dev:
    driver: bridge
services:
  app-demo:
    image: public.ecr.aws/j7i4j0s4/verificacion_api:latest
    #depends_on:
    # - "app_db"
    container_name: verificacion_api
    ports:
      - "5009:80"
    environment:
      #- ConnectionStrings__DefaultConnection=User ID =postgres;Password=postgres;Server=app_db;Port=5432;Database=SampleDriverDb; Integrated Security=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    



#version: '3.4'
#networks:
#  dev:
#    driver: bridge
#services:
#  app-demo:
#    image: public.ecr.aws/j7i4j0s4/verificacion_api:latest
#    #depends_on:
#    # - "app_db"
#    container_name: verificacion_api
#    ports:
#      - "5009:80"
#    #build:
#    #  context: .
#    #  dockerfile: Dockerfile
#    volumes:
#    - C:\Users\Tauro\.aws\credentials:/home/app/.aws/credentials
#    environment:
#      #- ConnectionStrings__DefaultConnection=User ID =postgres;Password=postgres;Server=app_db;Port=5432;Database=SampleDriverDb; Integrated Security=true;Pooling=true;
#      - ASPNETCORE_URLS=http://+:80
#    ##networks:
#    #  - dev
##  app_db:
##    image: postgres:14-alpine
##    ports:
##      - 5444:5432

##    environment:
##      - POSTGRES_PASSWORD=root
##      - POSTGRES_USER=postgres
##      - POSTGRES_DB=cars_db
##    volumes:
##      - app_data:/var/lib/postgresql/data
##    networks:
##      - dev
##volumes:
##  app_data: